<?php
$q = search_term(); $editId = (int)($_GET['edit'] ?? 0); $edit = $editId ? q_one("SELECT * FROM customers WHERE customer_id=?", 'i', [$editId]) : null;
$rows = $q === '' ? q_all("SELECT * FROM customers ORDER BY customer_id ASC") : q_all("SELECT * FROM customers WHERE customer_code LIKE ? OR first_name LIKE ? OR last_name LIKE ? OR city LIKE ? ORDER BY customer_id ASC", 'ssss', [like_term(), like_term(), like_term(), like_term()]);
?>
<div class="page-header"><div><h2 class="page-title">Customers</h2><div class="page-subtle">Manage customers</div></div></div>
<div class="split-layout">
<section class="panel"><h3><?= $edit ? 'Update Customer' : 'Add Customer' ?></h3><form method="post" action="actions/record.php" class="form-grid"><input type="hidden" name="entity" value="customers"><input type="hidden" name="id" value="<?= esc($edit['customer_id'] ?? '') ?>"><input type="hidden" name="customer_code" value="<?= esc($edit['customer_code'] ?? '') ?>"><input name="first_name" placeholder="First Name" value="<?= esc($edit['first_name'] ?? '') ?>" required><input name="last_name" placeholder="Last Name" value="<?= esc($edit['last_name'] ?? '') ?>" required><input type="date" name="date_of_birth" value="<?= esc($edit['date_of_birth'] ?? '') ?>" required><select name="gender"><option value="male" <?= (($edit['gender'] ?? '') === 'male') ? 'selected' : '' ?>>male</option><option value="female" <?= (($edit['gender'] ?? '') === 'female') ? 'selected' : '' ?>>female</option><option value="other" <?= (($edit['gender'] ?? '') === 'other') ? 'selected' : '' ?>>other</option></select><input name="phone" placeholder="Phone" value="<?= esc($edit['phone'] ?? '') ?>" required><input name="email" placeholder="Email" value="<?= esc($edit['email'] ?? '') ?>" required><input name="id_type" placeholder="ID Type (Aadhaar / PAN)" value="<?= esc($edit['id_type'] ?? '') ?>" required><input name="id_number" placeholder="ID Number" value="<?= esc($edit['id_number'] ?? '') ?>" required><input class="full" name="address_line" placeholder="Address" value="<?= esc($edit['address_line'] ?? '') ?>" required><input name="city" placeholder="City" value="<?= esc($edit['city'] ?? '') ?>" required><input name="state" placeholder="State" value="<?= esc($edit['state'] ?? '') ?>" required><input name="postal_code" placeholder="Postal Code" value="<?= esc($edit['postal_code'] ?? '') ?>" required><select name="status"><option value="active" <?= (($edit['status'] ?? 'active') === 'active') ? 'selected' : '' ?>>active</option><option value="inactive" <?= (($edit['status'] ?? '') === 'inactive') ? 'selected' : '' ?>>inactive</option></select><button type="submit"><?= $edit ? 'Update' : 'Create' ?></button></form></section>
<section class="panel"><form class="search-form" method="get"><input type="hidden" name="page" value="customers"><input name="q" placeholder="Search customers" value="<?= esc($q) ?>"><button type="submit">Search</button></form><div class="table-wrap"><table><thead><tr><th>ID</th><th>Code</th><th>Name</th><th>Phone</th><th>City</th><th>Status</th><th>Actions</th></tr></thead><tbody><?php foreach ($rows as $r): ?><tr><td><?= esc($r['customer_id']) ?></td><td><?= esc($r['customer_code']) ?></td><td><?= esc($r['first_name'] . ' ' . $r['last_name']) ?></td><td><?= esc($r['phone']) ?></td><td><?= esc($r['city']) ?></td><td><span class="badge <?= $r['status'] === 'active' ? 'approved' : 'closed' ?>"><?= esc($r['status']) ?></span></td><td><div class="action-row"><a href="index.php?page=customers&edit=<?= esc($r['customer_id']) ?>"><button type="button" class="btn-alt btn-small">Edit</button></a><form method="post" action="actions/record.php"><input type="hidden" name="entity" value="customers"><input type="hidden" name="mode" value="delete"><input type="hidden" name="id" value="<?= esc($r['customer_id']) ?>"><button class="btn-danger btn-small">Delete</button></form></div></td></tr><?php endforeach; ?></tbody></table></div>
<div class="mobile-list"><?php foreach ($rows as $r): ?><article class="record-card"><div class="record-grid"><div class="record-item"><div class="record-label">Code</div><div class="record-value"><?= esc($r['customer_code']) ?></div></div><div class="record-item"><div class="record-label">Name</div><div class="record-value"><?= esc($r['first_name'].' '.$r['last_name']) ?></div></div><div class="record-item"><div class="record-label">Phone</div><div class="record-value"><?= esc($r['phone']) ?></div></div><div class="record-item"><div class="record-label">City</div><div class="record-value"><?= esc($r['city']) ?></div></div><div class="record-item"><div class="record-label">Status</div><div class="record-value"><span class="badge <?= $r['status'] === 'active' ? 'approved' : 'closed' ?>"><?= esc($r['status']) ?></span></div></div></div><div class="action-row"><a href="index.php?page=customers&edit=<?= esc($r['customer_id']) ?>"><button type="button" class="btn-alt btn-small">Edit</button></a><form method="post" action="actions/record.php"><input type="hidden" name="entity" value="customers"><input type="hidden" name="mode" value="delete"><input type="hidden" name="id" value="<?= esc($r['customer_id']) ?>"><button class="btn-danger btn-small">Delete</button></form></div></article><?php endforeach; ?></div>
</section>
</div>
