<?php
$q = search_term(); $editId = (int)($_GET['edit'] ?? 0); $edit = $editId ? q_one("SELECT * FROM employees WHERE employee_id=?", 'i', [$editId]) : null;
$branches = q_all("SELECT branch_id, branch_name FROM branches ORDER BY branch_name ASC");
$roles = q_all("SELECT role_id, role_name FROM roles ORDER BY role_name ASC");
$rows = $q === '' ? q_all("SELECT e.*, b.branch_name, r.role_name FROM employees e JOIN branches b ON e.branch_id=b.branch_id JOIN roles r ON e.role_id=r.role_id ORDER BY e.employee_id ASC") : q_all("SELECT e.*, b.branch_name, r.role_name FROM employees e JOIN branches b ON e.branch_id=b.branch_id JOIN roles r ON e.role_id=r.role_id WHERE e.employee_code LIKE ? OR e.first_name LIKE ? OR e.last_name LIKE ? ORDER BY e.employee_id ASC", 'sss', [like_term(), like_term(), like_term()]);
?>
<div class="page-header"><div><h2 class="page-title">Employees</h2><div class="page-subtle">Manage employees</div></div></div>
<div class="split-layout">
<section class="panel"><h3><?= $edit ? 'Update Employee' : 'Add Employee' ?></h3><form method="post" action="actions/record.php" class="form-grid"><input type="hidden" name="entity" value="employees"><input type="hidden" name="id" value="<?= esc($edit['employee_id'] ?? '') ?>"><input type="hidden" name="employee_code" value="<?= esc($edit['employee_code'] ?? '') ?>"><input name="first_name" placeholder="First Name" value="<?= esc($edit['first_name'] ?? '') ?>" required><input name="last_name" placeholder="Last Name" value="<?= esc($edit['last_name'] ?? '') ?>" required><input class="full" name="email" placeholder="Email" value="<?= esc($edit['email'] ?? '') ?>" required><input name="phone" placeholder="Phone" value="<?= esc($edit['phone'] ?? '') ?>" required><input type="date" name="hire_date" value="<?= esc($edit['hire_date'] ?? date('Y-m-d')) ?>" required><select name="branch_id" required><?php foreach ($branches as $b): ?><option value="<?= $b['branch_id'] ?>" <?= (($edit['branch_id'] ?? '') == $b['branch_id']) ? 'selected' : '' ?>><?= esc($b['branch_name']) ?></option><?php endforeach; ?></select><select name="role_id" required><?php foreach ($roles as $r): ?><option value="<?= $r['role_id'] ?>" <?= (($edit['role_id'] ?? '') == $r['role_id']) ? 'selected' : '' ?>><?= esc($r['role_name']) ?></option><?php endforeach; ?></select><select name="status"><option value="active" <?= (($edit['status'] ?? 'active') === 'active') ? 'selected' : '' ?>>Active</option><option value="inactive" <?= (($edit['status'] ?? '') === 'inactive') ? 'selected' : '' ?>>Inactive</option></select><button type="submit"><?= $edit ? 'Update' : 'Create' ?></button></form></section>
<section class="panel"><form class="search-form" method="get"><input type="hidden" name="page" value="employees"><input name="q" placeholder="Search employees" value="<?= esc($q) ?>"><button type="submit">Search</button></form><div class="table-wrap"><table><thead><tr><th>Code</th><th>Name</th><th>Email</th><th>Role</th><th>Branch</th><th>Status</th><th>Actions</th></tr></thead><tbody><?php foreach ($rows as $r): ?><tr><td><?= esc($r['employee_code']) ?></td><td><?= esc($r['first_name'] . ' ' . $r['last_name']) ?></td><td><?= esc($r['email']) ?></td><td><?= esc($r['role_name']) ?></td><td><?= esc($r['branch_name']) ?></td><td><span class="badge <?= $r['status'] === 'active' ? 'approved' : 'closed' ?>"><?= esc($r['status']) ?></span></td><td><div class="action-row"><a href="index.php?page=employees&edit=<?= esc($r['employee_id']) ?>"><button type="button" class="btn-alt btn-small">Edit</button></a><form method="post" action="actions/record.php"><input type="hidden" name="entity" value="employees"><input type="hidden" name="mode" value="delete"><input type="hidden" name="id" value="<?= esc($r['employee_id']) ?>"><button class="btn-danger btn-small">Delete</button></form></div></td></tr><?php endforeach; ?></tbody></table></div>
<div class="mobile-list"><?php foreach ($rows as $r): ?><article class="record-card"><div class="record-grid"><div class="record-item"><div class="record-label">Code</div><div class="record-value"><?= esc($r['employee_code']) ?></div></div><div class="record-item"><div class="record-label">Name</div><div class="record-value"><?= esc($r['first_name'].' '.$r['last_name']) ?></div></div><div class="record-item"><div class="record-label">Role</div><div class="record-value"><?= esc($r['role_name']) ?></div></div><div class="record-item"><div class="record-label">Branch</div><div class="record-value"><?= esc($r['branch_name']) ?></div></div><div class="record-item"><div class="record-label">Status</div><div class="record-value"><span class="badge <?= $r['status'] === 'active' ? 'approved' : 'closed' ?>"><?= esc($r['status']) ?></span></div></div></div><div class="action-row"><a href="index.php?page=employees&edit=<?= esc($r['employee_id']) ?>"><button type="button" class="btn-alt btn-small">Edit</button></a><form method="post" action="actions/record.php"><input type="hidden" name="entity" value="employees"><input type="hidden" name="mode" value="delete"><input type="hidden" name="id" value="<?= esc($r['employee_id']) ?>"><button class="btn-danger btn-small">Delete</button></form></div></article><?php endforeach; ?></div>
</section>
</div>
