<?php
$q = search_term(); $editId = (int)($_GET['edit'] ?? 0); $edit = $editId ? q_one("SELECT * FROM loans WHERE loan_id=?", 'i', [$editId]) : null;
$customers = q_all("SELECT customer_id, customer_code, first_name, last_name FROM customers WHERE status='active' ORDER BY customer_id ASC");
$branches = q_all("SELECT branch_id, branch_name FROM branches ORDER BY branch_id ASC");
$types = q_all("SELECT loan_type_id, type_name, default_interest_rate FROM loan_types ORDER BY type_name ASC");
$rows = $q === '' ? q_all("SELECT l.loan_id,l.loan_number,l.principal_amount,l.interest_rate,l.tenure_months,l.start_date,l.status,lt.type_name,CONCAT(c.first_name,' ',c.last_name) AS customer_name,COALESCE(SUM(lp.amount_paid),0) AS total_paid FROM loans l JOIN loan_types lt ON l.loan_type_id=lt.loan_type_id JOIN customers c ON l.customer_id=c.customer_id LEFT JOIN loan_payments lp ON l.loan_id=lp.loan_id GROUP BY l.loan_id,l.loan_number,l.principal_amount,l.interest_rate,l.tenure_months,l.start_date,l.status,lt.type_name,c.first_name,c.last_name ORDER BY l.loan_id DESC") : q_all("SELECT l.loan_id,l.loan_number,l.principal_amount,l.interest_rate,l.tenure_months,l.start_date,l.status,lt.type_name,CONCAT(c.first_name,' ',c.last_name) AS customer_name,COALESCE(SUM(lp.amount_paid),0) AS total_paid FROM loans l JOIN loan_types lt ON l.loan_type_id=lt.loan_type_id JOIN customers c ON l.customer_id=c.customer_id LEFT JOIN loan_payments lp ON l.loan_id=lp.loan_id WHERE l.loan_number LIKE ? OR c.first_name LIKE ? OR lt.type_name LIKE ? GROUP BY l.loan_id,l.loan_number,l.principal_amount,l.interest_rate,l.tenure_months,l.start_date,l.status,lt.type_name,c.first_name,c.last_name ORDER BY l.loan_id DESC", 'sss', [like_term(), like_term(), like_term()]);
?>
<div class="page-header"><div><h2 class="page-title">Loans</h2><div class="page-subtle">Manage loans</div></div></div>
<div class="split-layout">
<section class="panel"><h3><?= $edit ? 'Update Loan' : 'Add Loan' ?></h3><form method="post" action="actions/record.php" class="form-grid"><input type="hidden" name="entity" value="loans"><input type="hidden" name="id" value="<?= esc($edit['loan_id'] ?? '') ?>"><input type="hidden" name="loan_number" value="<?= esc($edit['loan_number'] ?? '') ?>"><select class="full" name="customer_id" required><option value="">— Select Customer —</option><?php foreach ($customers as $c): ?><option value="<?= $c['customer_id'] ?>" <?= (($edit['customer_id'] ?? '') == $c['customer_id']) ? 'selected' : '' ?>><?= esc($c['first_name'] . ' ' . $c['last_name'] . ' (' . $c['customer_code'] . ')') ?></option><?php endforeach; ?></select><select name="branch_id" required><?php foreach ($branches as $b): ?><option value="<?= $b['branch_id'] ?>" <?= (($edit['branch_id'] ?? '') == $b['branch_id']) ? 'selected' : '' ?>><?= esc($b['branch_name']) ?></option><?php endforeach; ?></select><select name="loan_type_id" required><?php foreach ($types as $t): ?><option value="<?= $t['loan_type_id'] ?>" <?= (($edit['loan_type_id'] ?? '') == $t['loan_type_id']) ? 'selected' : '' ?>><?= esc($t['type_name'] . ' (' . $t['default_interest_rate'] . '%)') ?></option><?php endforeach; ?></select><input type="number" step="0.01" name="principal_amount" placeholder="Principal Amount" value="<?= esc($edit['principal_amount'] ?? '') ?>" required><input type="number" step="0.01" name="interest_rate" placeholder="Interest Rate (%)" value="<?= esc($edit['interest_rate'] ?? '') ?>" required><input type="number" name="tenure_months" placeholder="Tenure (months)" value="<?= esc($edit['tenure_months'] ?? '') ?>" required><input type="date" name="start_date" value="<?= esc($edit['start_date'] ?? date('Y-m-d')) ?>" required><select name="status"><option value="pending" <?= (($edit['status'] ?? '') === 'pending') ? 'selected' : '' ?>>Pending</option><option value="approved" <?= (($edit['status'] ?? 'approved') === 'approved') ? 'selected' : '' ?>>Approved</option><option value="active" <?= (($edit['status'] ?? '') === 'active') ? 'selected' : '' ?>>Active</option><option value="closed" <?= (($edit['status'] ?? '') === 'closed') ? 'selected' : '' ?>>Closed</option><option value="rejected" <?= (($edit['status'] ?? '') === 'rejected') ? 'selected' : '' ?>>Rejected</option></select><button type="submit"><?= $edit ? 'Update' : 'Create' ?></button></form></section>
<section class="panel"><form class="search-form" method="get"><input type="hidden" name="page" value="loans"><input name="q" placeholder="Search loans" value="<?= esc($q) ?>"><button type="submit">Search</button></form><div class="table-wrap"><table><thead><tr><th>Number</th><th>Customer</th><th>Type</th><th>Principal</th><th>Rate</th><th>Tenure</th><th>Paid</th><th>Status</th><th>Actions</th></tr></thead><tbody><?php foreach ($rows as $r): $pct = (float)$r['principal_amount'] > 0 ? round(((float)$r['total_paid'] / (float)$r['principal_amount']) * 100, 1) : 0; ?><tr><td><?= esc($r['loan_number']) ?></td><td><?= esc($r['customer_name']) ?></td><td><?= esc($r['type_name']) ?></td><td><?= esc(number_format((float)$r['principal_amount'],2)) ?></td><td><?= esc($r['interest_rate']) ?>%</td><td><?= esc($r['tenure_months']) ?> mo</td><td><div><?= esc(number_format((float)$r['total_paid'],2)) ?></div><div class="progress-bar-wrap progress-bar-sm"><div class="progress-bar" style="width:<?= min($pct,100) ?>%"></div></div></td><td><span class="badge <?= esc($r['status']) ?>"><?= esc($r['status']) ?></span></td><td><div class="action-row"><a href="index.php?page=loans&edit=<?= esc($r['loan_id']) ?>"><button type="button" class="btn-alt btn-small">Edit</button></a><form method="post" action="actions/record.php"><input type="hidden" name="entity" value="loans"><input type="hidden" name="mode" value="delete"><input type="hidden" name="id" value="<?= esc($r['loan_id']) ?>"><button class="btn-danger btn-small">Delete</button></form></div></td></tr><?php endforeach; ?></tbody></table></div>
<div class="mobile-list"><?php foreach ($rows as $r): ?><article class="record-card"><div class="record-grid"><div class="record-item"><div class="record-label">Loan</div><div class="record-value"><?= esc($r['loan_number']) ?></div></div><div class="record-item"><div class="record-label">Customer</div><div class="record-value"><?= esc($r['customer_name']) ?></div></div><div class="record-item"><div class="record-label">Principal</div><div class="record-value"><?= esc(number_format((float)$r['principal_amount'],2)) ?></div></div><div class="record-item"><div class="record-label">Status</div><div class="record-value"><span class="badge <?= esc($r['status']) ?>"><?= esc($r['status']) ?></span></div></div></div><div class="action-row"><a href="index.php?page=loans&edit=<?= esc($r['loan_id']) ?>"><button type="button" class="btn-alt btn-small">Edit</button></a><form method="post" action="actions/record.php"><input type="hidden" name="entity" value="loans"><input type="hidden" name="mode" value="delete"><input type="hidden" name="id" value="<?= esc($r['loan_id']) ?>"><button class="btn-danger btn-small">Delete</button></form></div></article><?php endforeach; ?></div>
</section>
</div>
