<?php
$q = search_term(); $editId = (int)($_GET['edit'] ?? 0); $edit = $editId ? q_one("SELECT * FROM transactions WHERE transaction_id=?", 'i', [$editId]) : null;
$employees = q_all("SELECT employee_id, employee_code, first_name, last_name FROM employees WHERE status='active' ORDER BY employee_id ASC");
$accounts = q_all("SELECT a.account_id, a.account_number, CONCAT(c.first_name,' ',c.last_name) AS holder FROM accounts a JOIN account_holders ah ON a.account_id=ah.account_id AND ah.holder_role='primary' JOIN customers c ON ah.customer_id=c.customer_id WHERE a.status='active' ORDER BY a.account_id ASC");
$rows = $q === '' ? q_all("SELECT t.transaction_id,t.reference_no,t.amount,t.transaction_date,t.narration,tt.type_name,sa.account_number AS source_account,ta.account_number AS target_account,CONCAT(e.first_name,' ',e.last_name) AS handled_by FROM transactions t JOIN transaction_types tt ON t.transaction_type_id=tt.transaction_type_id LEFT JOIN accounts sa ON t.source_account_id=sa.account_id LEFT JOIN accounts ta ON t.target_account_id=ta.account_id LEFT JOIN employees e ON t.initiated_by=e.employee_id ORDER BY t.transaction_date DESC,t.transaction_id DESC") : q_all("SELECT t.transaction_id,t.reference_no,t.amount,t.transaction_date,t.narration,tt.type_name,sa.account_number AS source_account,ta.account_number AS target_account,CONCAT(e.first_name,' ',e.last_name) AS handled_by FROM transactions t JOIN transaction_types tt ON t.transaction_type_id=tt.transaction_type_id LEFT JOIN accounts sa ON t.source_account_id=sa.account_id LEFT JOIN accounts ta ON t.target_account_id=ta.account_id LEFT JOIN employees e ON t.initiated_by=e.employee_id WHERE t.reference_no LIKE ? OR tt.type_name LIKE ? OR t.narration LIKE ? ORDER BY t.transaction_date DESC,t.transaction_id DESC", 'sss', [like_term(), like_term(), like_term()]);
$currentType = $edit ? (q_one("SELECT type_name FROM transaction_types WHERE transaction_type_id=?", 'i', [$edit['transaction_type_id']])['type_name'] ?? 'Cash Deposit') : 'Cash Deposit';
?>
<div class="page-header"><div><h2 class="page-title">Transactions</h2><div class="page-subtle">Manage transactions</div></div></div>
<div class="split-layout">
<section class="panel"><h3><?= $edit ? 'Update Transaction' : 'Add Transaction' ?></h3><form method="post" action="actions/record.php" class="form-grid"><input type="hidden" name="entity" value="transactions"><input type="hidden" name="id" value="<?= esc($edit['transaction_id'] ?? '') ?>"><input type="hidden" name="reference_no" value="<?= esc($edit['reference_no'] ?? '') ?>"><select class="full" name="type_name"><option value="Cash Deposit" <?= $currentType==='Cash Deposit'?'selected':'' ?>>Cash Deposit</option><option value="Cash Withdrawal" <?= $currentType==='Cash Withdrawal'?'selected':'' ?>>Cash Withdrawal</option><option value="Account Transfer" <?= $currentType==='Account Transfer'?'selected':'' ?>>Account Transfer</option></select><select name="initiated_by" required><option value="">— Select Employee —</option><?php foreach ($employees as $e): ?><option value="<?= $e['employee_id'] ?>" <?= (($edit['initiated_by'] ?? '') == $e['employee_id']) ? 'selected' : '' ?>><?= esc($e['employee_code'] . ' — ' . $e['first_name'] . ' ' . $e['last_name']) ?></option><?php endforeach; ?></select><select name="source_account_id"><option value="">— Source Account (for withdrawal/transfer) —</option><?php foreach ($accounts as $a): ?><option value="<?= $a['account_id'] ?>" <?= (($edit['source_account_id'] ?? '') == $a['account_id']) ? 'selected' : '' ?>><?= esc($a['account_number'] . ' — ' . $a['holder']) ?></option><?php endforeach; ?></select><select name="target_account_id"><option value="">— Target Account (for deposit/transfer) —</option><?php foreach ($accounts as $a): ?><option value="<?= $a['account_id'] ?>" <?= (($edit['target_account_id'] ?? '') == $a['account_id']) ? 'selected' : '' ?>><?= esc($a['account_number'] . ' — ' . $a['holder']) ?></option><?php endforeach; ?></select><input type="number" step="0.01" name="amount" placeholder="Amount" value="<?= esc($edit['amount'] ?? '') ?>" required><input class="full" name="narration" placeholder="Narration / Description" value="<?= esc($edit['narration'] ?? '') ?>" required><input class="full" type="datetime-local" name="transaction_date" value="<?= isset($edit['transaction_date']) ? esc(str_replace(' ', 'T', $edit['transaction_date'])) : date('Y-m-d\TH:i') ?>" required><button type="submit"><?= $edit ? 'Update' : 'Create' ?></button></form></section>
<section class="panel"><form class="search-form" method="get"><input type="hidden" name="page" value="transactions"><input name="q" placeholder="Search transactions" value="<?= esc($q) ?>"><button type="submit">Search</button></form><div class="table-wrap"><table><thead><tr><th>Ref.</th><th>Type</th><th>Source</th><th>Target</th><th>Amount</th><th>Handled By</th><th>Date</th><th>Actions</th></tr></thead><tbody><?php foreach ($rows as $r): ?><tr><td><span class="badge approved"><?= esc($r['reference_no']) ?></span></td><td><?= esc($r['type_name']) ?></td><td><?= esc($r['source_account'] ?: '—') ?></td><td><?= esc($r['target_account'] ?: '—') ?></td><td><?= esc(number_format((float)$r['amount'],2)) ?></td><td><?= esc($r['handled_by'] ?: '—') ?></td><td><?= esc(date('d M Y H:i', strtotime($r['transaction_date']))) ?></td><td><div class="action-row"><a href="index.php?page=transactions&edit=<?= esc($r['transaction_id']) ?>"><button type="button" class="btn-alt btn-small">Edit</button></a><form method="post" action="actions/record.php"><input type="hidden" name="entity" value="transactions"><input type="hidden" name="mode" value="delete"><input type="hidden" name="id" value="<?= esc($r['transaction_id']) ?>"><button class="btn-danger btn-small">Delete</button></form></div></td></tr><?php endforeach; ?></tbody></table></div>
<div class="mobile-list"><?php foreach ($rows as $r): ?><article class="record-card"><div class="record-grid"><div class="record-item"><div class="record-label">Ref</div><div class="record-value"><?= esc($r['reference_no']) ?></div></div><div class="record-item"><div class="record-label">Type</div><div class="record-value"><?= esc($r['type_name']) ?></div></div><div class="record-item"><div class="record-label">Amount</div><div class="record-value"><?= esc(number_format((float)$r['amount'],2)) ?></div></div><div class="record-item"><div class="record-label">Date</div><div class="record-value"><?= esc(date('d M Y', strtotime($r['transaction_date']))) ?></div></div></div><div class="action-row"><a href="index.php?page=transactions&edit=<?= esc($r['transaction_id']) ?>"><button type="button" class="btn-alt btn-small">Edit</button></a><form method="post" action="actions/record.php"><input type="hidden" name="entity" value="transactions"><input type="hidden" name="mode" value="delete"><input type="hidden" name="id" value="<?= esc($r['transaction_id']) ?>"><button class="btn-danger btn-small">Delete</button></form></div></article><?php endforeach; ?></div>
</section>
</div>
